apiVersion: v1
kind: Service
metadata:
  name: tomcataks
  namespace: namespace-workflow-1694896099551
spec:
  type: LoadBalancer
  selector:
    app: tomcataks
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080